### ISSUE TITLE
uBlock Origin filter

### ISSUE THREAD

**Issue by Anonymous941** [zbarnz/Google_AI_Overviews_Blocker#5]
Thanks for making this extension!  Here is a uBlock Origin filter that's similar:
```plain
google.com##div:has(> h1:has-text(/^AI Overview$/))
```
Not sure if it's faster or slower, but maybe it could be on the README or something as an alternative

**Comment by zbarnz** [comment]
Thank you for your input! I'm glad you're finding the extension helpful. While the filter is a great alternative for uBlock users, I want to keep this project focused specifically on providing a one-click solution without needing additional setup.
